added pages/test workflow in deply yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -19,10 +19,66 @@ jobs:
       - name: Install dependencies
         run: npm install
 
-      - name: Run test
+      - name: Run tests
         run: npm test
 
       - name: Upload coverage to Codecov
         uses: codecov/codecov-action@v4
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
+
+  check-coverage:
+    runs-on: ubuntu-latest
+    needs: test
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Check test coverage
+        run: /
+          if [ ! -f ./coverage/coverage-summary.json ]; then
+            echo "Coverage report not found"
+            exit 1
+          fi 
+
+          echo "Coverage report found"
+
+          COVERAGE=$(cat ./coverage/coverage-summary.json | jq .total.lines.pct)
+          echo "Test covarage is ${COVERAGE}%"
+
+          if (( $(echo "$COVERAGE < 85" | bc -l) )); then
+            echo "Test coverage is below 85%, cannot deploy."
+            exit 1
+          fi
+
+  deploy:
+    runs-on: ubuntu-latest
+    needs: check-coverage
+    permissions:
+      contents: read
+      pages: write
+      id-token: write
+
+    steps: 
+      - uses: actions/checkout@v4
+      - name: Install modules
+        run: npm install
+
+      - name: Build dist
+        run: npm run build
+
+      - name: Setup pages
+        uses: actions/configure-pages@v3
+
+      - name: Upload dist folder
+        uses: action/upload-pages-artifact@v1
+        with:
+          path: "./dist"
+        
+      - name: Deploy to github pages
+        id: deployment
+        uses: action/deploy-pages@v1
+
+      
+
